sparkmaster:
  image: loki2302/sparkmaster
  hostname: sparkmaster
  links:
    - zookeeper
    - kafka
  ports:
    - "8080:8080"
    - "7077:7077"

sparkworker1:
  image: loki2302/sparkworker
  hostname: sparkworker1
  environment:
    SPARK_MASTER: "sparkmaster:7077"
    WEBUI_PORT: 8081
    CORES: 2
  links:
    - sparkmaster
    - zookeeper
    - kafka
  ports:
    - "8081:8081"

zookeeper:
  image: jplock/zookeeper:3.4.6
  hostname: zookeeper
  ports:
    - "2181:2181"

kafka:
  image: wurstmeister/kafka:0.8.2.1
  hostname: kafka
  ports:
    - "9092:9092"
  links:
    - zookeeper
  environment:
    KAFKA_ADVERTISED_HOST_NAME: kafka
    KAFKA_ADVERTISED_PORT: 9092
    KAFKA_BROKER_ID: 0
    KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
